{{- if .Values.threeTierApp.deploy }}
{{- with .Values.threeTierApp }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .releaseName }}
  namespace: argocd       
spec:
  project: default        
  source:
  - repoURL: {{ .sourceUrl }}
    targetRevision: main
    path: web-app-argocdApp
    ref: values
  - repoURL: {{ .sourceUrl }}
    targetRevision: main
    path: {{ .repoName }}
    {{- if $.Values.customValues }}
    helm:
      valueFiles:
        - $values/values.yaml
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}      
  syncPolicy:
    automated:            
      prune: true          
      selfHeal: true       
    syncOptions:           
      - CreateNamespace=true 
{{- end }}
{{- end }}
