{{- if .Values.threeTierApp.deploy }}
{{- with .Values.threeTierApp }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .releaseName }}
  namespace: argocd       
spec:
  project: default        
  sources:
  - repoURL: {{ .sourceUrl }}
    targetRevision: main
    ref: values
  - repoURL: {{ .sourceUrl }}
    targetRevision: main
    path: {{ .repoName }}
    {{- if $.Values.customValues }}
    helm:
      valueFiles:
        - $values/web-app-argocdApp/values.yaml
    {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}      
  syncPolicy:
    {{- toYaml .syncPolicy | nindent 4 }}
{{- end }}
{{- end }}
