{{- if .Values.3tier-app.deploy }}
{{- with .Values.3tier-app }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .releaseName }}
  namespace: argocd       
spec:
  project: default        
  source:
    repoURL: {{ .sourceUrl }}
    targetRevision: main
    path: {{ .repoName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .namespace }}      
  syncPolicy:
    automated:            
      prune: true          
      selfHeal: true       
    syncOptions:           
      - CreateNamespace=true 
{{- end }}
{{- end }}
