apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-es
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    name: {{ .Release.Name }}-secretstore
    kind: SecretStore
  target:
    name: {{ .Values.postgresql.auth.existingSecret }}
  data:
    - secretKey: {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}
      remoteRef: 
        key: {{ .Values.secretStore.remoteRefKey }} 
        property: {{ .Values.secretStore.remoteRefProperty }}