apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-secretstore
  namespace: {{ .Release.Namespace }}
spec:
  provider:
      aws:
        service: SecretsManager
        {{- with .Values.secretStore }}
        region: {{ .region }}
        auth:
          secretRef:
            accessKeyIDSecretRef:
              name: {{ .awscred }}  
              key: access-key
            secretAccessKeySecretRef:
              name: {{ .awscred }}
              key: secret-key
        {{- end }}