apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  labels:
    app: webapp
data:
  app.py: |
{{ .Files.Get "app.py" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
data:
  {{ include "example.nested" .Values | nindent 2}}
  