apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-es
  namespace: default
spec:
  secretStoreRef:
    name: {{ .Release.Name }}-secretstore
    kind: SecretStore
  target:
    name: {{ .Values.targetSecretName }}
  data:
    - secretKey: redis-password
      remoteRef: 
        key: webapp/redis-password 
        property: redis-password

