threeTierApp:
  deploy: true 
  releaseName: web-app-application
  sourceUrl: https://github.com/YulianBortsov/helm-practice.git
  repoName: 3tier-app
  namespace: 3tier-app

customValues: true

frontend:
  replicaCount: 3 