apiVersion: v1
kind: ConfigMap
metadata:
  name: app-cm-backend
data:
  app.py: |
{{ .Files.Get "code/app.py" | indent 4 }}
---
apiVersion: v1
data:
  requirements.txt: |
{{ .Files.Get "code/requirements.txt" | nindent 4 }}
kind: ConfigMap
metadata:
  name: requirements-cm-backend