apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    app: {{ .Release.Name }}-backend
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          command: ["/bin/bash", "-c"]
          args:
            - pip install -r /app/requirements.txt && python /app/app.py;   
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: {{ .Release.Name }}-postgresql
            - name: DATABASE_USER
              value: {{ .Values.backend.env.DATABASE_USER | quote }}
            - name: DATABASE_PASSWORD
              valueFrom:
                secretRefKey:
                  name: {{ .Values.postgresql.auth.existingSecret }}
                  key: {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}
            - name: DATABASE_NAME
              value: {{ .Values.backend.env.DATABASE_NAME | quote }}
          volumeMounts:
            {{- toYaml .Values.backend.volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .Values.backend.volumes | nindent 8 }}