{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  first_env: {{ .Values.configMap.first }}
  second_env: {{ .Values.configMap.second }}
{{- end }}
  