{{- if .Values.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
spec:
  accessModes:                     # Specifies how the volume can be accessed
    - ReadWriteOnce                # Options: ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.pvc.storageRequest }}               # Storage size requested
#  storageClassName: standard       # The StorageClass to use (if dynamic provisioning is enabled)
{{- end }}