apiVersion: v1
kind: Service
metadata:
  name: helm-cluster-ip
spec:
  type: {{ .Values.service.type }}
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: helm-nodeport
spec:
  type: NodePort
  selector:
    app: {{ .Values.app }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.nodePort }}